version: "3"
services:
  app:
    image: golang:1.22.2
    volumes:
    - ./:/app
    ports:
    - "8080:8080"
    working_dir: /app
    command: sleep infinity
    environment:
      - DB_HOST=db
      - DB_USER=test_user
      - DB_PASSWORD=test_password
      - DB_NAME=test_db
  db:
    image: mariadb:lts
    environment:
      - MARIADB_ROOT_PASSWORD=dev
      - MARIADB_DATABASE=test_db
      - MARIADB_USER=test_user
      - MARIADB_PASSWORD=test_password
  phpmyadmin:
    image: phpmyadmin
    ports:
    - 8090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=dev
